Repository neutrinoceros/gpgi, pull requests merged in 2024-09, with the labels that each got.

#255 DOC: Fix toc in documentation and a typo
  .pre-commit-config.yaml
  README.md
Labels: documentation

#261 DOC: add missing versionadded/versionchanged to docstrings
  README.md
  src/gpgi/types.py
Labels: documentation

#256 API: clearly define public/private APIs
  README.md
  src/gpgi/__init__.py
  src/gpgi/_boundaries.py
  src/gpgi/_data_types.py
  src/gpgi/_load.py
  src/gpgi/typing.py
  tests/test_deposit.py
Labels: API

#263 DOC: document thread-safety of `BoundaryRegistry`
  README.md
Labels: documentation

#264 MNT: fixup coverage reporting
  .github/workflows/ci.yml
Labels: bug, github_actions

#270 TST: pin uv to 0.4.9
  .github/workflows/ci.yml
Labels: tests
